/*************************************************
 * Single_node_tester<Object>
 * A class for testing nodes used in singly-linked lists.
 *
 * Author:  Douglas Wilhelm Harder
 * Copyright (c) 2006-2010 by Douglas Wilhelm Harder.  All rights reserved.
 *
 * DO NOT EDIT THIS FILE
 *************************************************/

#ifndef SINGLE_NODE_TESTER_H    // include guards
#define SINGLE_NODE_TESTER_H

#include "Exception.h"
#include "Tester.h"
#include "Single_node.h"

#include <iostream>

template <typename Object>
class Single_node_tester:public Tester< Single_node<Object> > {
	using Tester< Single_node<Object> >::object;
	using Tester< Single_node<Object> >::command;

	public:
		Single_node_tester( Single_node<Object> *obj = 0 ):Tester< Single_node<Object> >( obj ) {
			// empty
		}

		void process();
};

/****************************************************
 * void process()
 *
 * Process the current command.  For single nodes, these include:
 *
 *                 Member 
 *   Flag         Function         Tests if ...
 *
 *  Accessors
 *
 *   next          next()          the next pointer can be followed
 *   next0         next()          the next pointer is 0
 *   retrieve n    retrieve()      the stored value is n
 ****************************************************/

template <typename Object>
void Single_node_tester<Object>::process() {
	if ( command == "next" ) {
		Single_node<Object> *actual_next = Single_node_tester<Object>::object->next();

		if ( actual_next != 0 ) {
			object = actual_next;
			std::cout << "Okay" << std::endl;
		} else {
			std::cout << ": Failure in next(): expecting to follow a non-null next pointer" << std::endl;
		}
	} else if ( command == "next0" ) {
		if ( object->next() == 0 ) {
			std::cout << "Okay" << std::endl;
		} else {
			std::cout << ": Failure in next(): expecting a null (0) next pointer" << std::endl;
		}
	} else if ( command == "retrieve" ) {
		Object expected_value;
		std::cin >> expected_value;

		Object actual_value;
		actual_value = object->retrieve();

		if ( expected_value == actual_value ) {
			std::cout << "Okay" << std::endl;
		} else {
			std::cout << ": Failure in retrieve(): expecting '" << expected_value <<
				"' but got '" << actual_value << "'" << std::endl;
		}
	} else {
		std::cout << command << ": Command not found." << std::endl;
	}
}
#endif
